### PR TITLE
Markdown tag for underline (==)

### PR DESCRIPTION
**Pull request by haidalinda**
* Added support for new Markdown tag - `==` for underlining
* Added `underlineStyle` and `underlineColor` to `TextStyle`
* Updated `TextStyle` factory functions to include new properties
* Tests

### CODE REVIEW

**Comment by ThibaultKlein** [comment]
Looks like the tests are failing

**Comment by haidalinda** [comment]
tests are passing

**Review by ThibaultKlein — APPROVED** [review]

**Comment by htinlinn** [comment]
@hkellaway is `==` a common Markdown tag used for underline? I have never actually come across it before...

**Comment by haidalinda** [comment]
there isn't one from what i can tell

**Comment by htinlinn** [comment]
@hkellaway hmm. Maybe I am overthinking this a bit but should we note that in the README? Come to think of it, I don't think `~~` for strikethrough is official either: https://daringfireball.net/projects/markdown/syntax

**Comment by haidalinda** [comment]
just updated the README

**Review by htinlinn — APPROVED** [review]

**Pull request merged**
